#!/bin/env perl
use strict;
use Logwatch ':dates';

my $ThisLine;
my $SearchDate = TimeFilter('%d-%b-%Y %H:%M:%S\.[0-9]*');
my $Filter = qr/,$SearchDate,/;

# To start with, just output any ERROR or WARNing lines ...

while (defined($ThisLine = <STDIN>)) {
    if ($ThisLine =~ $Filter) {
	if ($ThisLine =~ /\[.*ERROR.*\](.*)/oi) {
	    print "$ThisLine\n";
	} elsif ($ThisLine =~ /\[.*WARN.*\](.*)/oi) {
	    print "$ThisLine\n";
	}
    }
}
